apiVersion: v2
name: monitoring
description: A Helm chart for monitoring stack (Prometheus, Grafana, Alertmanager) on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - metrics
  - observability
home: https://prometheus.io
sources:
  - https://github.com/prometheus/prometheus
  - https://github.com/grafana/grafana
maintainers:
  - name: Data Team
    email: data-team@company.com
